services:
  app:
    build:
      context: D:\Cloud\esp32_iot\Chapter_16\project
      dockerfile: Dockerfile
    depends_on:
      mosquitto:
        condition: service_started
        required: true
      mysql:
        condition: service_started
        required: true
    environment:
      MYSQL_DB: esp_data
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: test
      MYSQL_USER: root
    networks:
      mynetwork: null
    ports:
      - mode: ingress
        target: 5000
        published: "5000"
        protocol: tcp
