services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
    
    ports:
      - "5001:5001"
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: iot_smart_classroom_db
      POSTGRES_USER: miso
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U miso -d iot_smart_classroom_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mynetwork
    ports:
      - "1883:1883"
      - "9001:9001"

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
